# Generated by Django 3.1.7 on 2021-05-13 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_institute', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Email')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassMaterial',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('material', models.FileField(upload_to='learnerApp/material')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('classroom_image', models.ImageField(blank=True, upload_to='learnerApp/classsroom_images')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('course_image', models.ImageField(blank=True, upload_to='learnerApp/classsroom_images')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learnerApp.customuser')),
                ('first_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Last Name')),
                ('admin_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile Number')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='learnerApp/profile_images/admin')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learnerApp.customuser')),
                ('institute_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Institute Name')),
                ('institute_address', models.TextField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('institute_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Mobile Number')),
                ('institute_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Institute Id')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='learnerApp/profile_images/institute')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('video_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('decription', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.FileField(upload_to='learnerApp/videos')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMaterialMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.classmaterial')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classmaterial',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.classroom'),
        ),
        migrations.CreateModel(
            name='ClassFeedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.classroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learnerApp.customuser')),
                ('student_id', models.CharField(blank=True, max_length=75, null=True, verbose_name='Student ID')),
                ('first_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Last Name')),
                ('student_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile Number')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='learnerApp/profile_images/student')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.institute')),
            ],
            options={
                'unique_together': {('student_id', 'institute')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learnerApp.customuser')),
                ('faculty_id', models.CharField(blank=True, max_length=75, null=True, verbose_name='Faculty Id')),
                ('first_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Last Name')),
                ('faculty_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile Number')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='learnerApp/profile_images/faculty')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.institute')),
            ],
            options={
                'unique_together': {('faculty_id', 'institute')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='learnerApp.Student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.faculty'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classrooms', to='learnerApp.Student'),
        ),
    ]
