# Generated by Django 3.1.2 on 2021-04-29 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_institute', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Email')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learnerApp.customuser')),
                ('first_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Last Name')),
                ('admin_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learnerApp.customuser')),
                ('institute_name', models.CharField(max_length=75, verbose_name='Institute Name')),
                ('institute_address', models.TextField(max_length=100, verbose_name='Address')),
                ('institute_number', models.PositiveBigIntegerField(blank=True, verbose_name='Mobile Number')),
                ('institute_id', models.IntegerField(unique=True, verbose_name='Institute Id')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learnerApp.customuser')),
                ('student_id', models.CharField(max_length=75, verbose_name='Student ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=75, verbose_name='Last Name')),
                ('student_number', models.PositiveIntegerField(blank=True, verbose_name='Mobile Number')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.institute')),
            ],
            options={
                'unique_together': {('student_id', 'institute')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learnerApp.customuser')),
                ('faculty_id', models.CharField(max_length=75, verbose_name='Faculty Id')),
                ('first_name', models.CharField(max_length=75, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=75, verbose_name='Last Name')),
                ('faculty_number', models.PositiveIntegerField(blank=True, verbose_name='Mobile Number')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.institute')),
            ],
            options={
                'unique_together': {('faculty_id', 'institute')},
            },
        ),
    ]
