# Generated by Django 3.1.2 on 2021-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Faculty Id'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='first_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Institute Id'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Institute Name'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile Number'),
        ),
    ]
