# Generated by Django 3.1.7 on 2021-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user_image',
            field=models.ImageField(blank=True, default=None, upload_to='learnerApp/profile_images/admin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='learnerApp/profile_images/faculty'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='learnerApp/profile_images/institute'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='learnerApp/profile_images/student'),
        ),
    ]
