# Generated by Django 3.1.7 on 2021-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerApp', '0002_auto_20210513_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='learnerApp.Student'),
        ),
    ]
