# Generated by Django 3.1.7 on 2021-05-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnerApp', '0003_auto_20210513_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursevideo',
            old_name='decription',
            new_name='description',
        ),
    ]
