# Generated by Django 3.1.7 on 2021-05-13 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnerApp', '0004_auto_20210514_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('response_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionResponse',
            fields=[
                ('q_response_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.testresponse')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=50)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.test')),
            ],
        ),
    ]
