# Generated by Django 3.1.7 on 2021-05-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerApp', '0005_test_testquestion_testquestionresponse_testresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
