# Generated by Django 3.1.7 on 2021-05-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnerApp', '0007_auto_20210514_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestionresponse',
            name='question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='learnerApp.testquestion'),
            preserve_default=False,
        ),
    ]
