# Generated by Django 3.1.7 on 2021-05-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnerApp', '0008_testquestionresponse_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testquestionresponse',
            old_name='question_id',
            new_name='question',
        ),
    ]
