# Generated by Django 3.1.7 on 2021-05-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnerApp', '0009_auto_20210514_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTest',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learnerApp.course')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTestQuestion',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=50)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.coursetest')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTestResponse',
            fields=[
                ('response_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.coursetest')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTestQuestionResponse',
            fields=[
                ('q_response_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.coursetestquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerApp.coursetestresponse')),
            ],
        ),
    ]
